# Generated by Django 5.0.8 on 2024-08-24 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
